# Scripts to install essential extension for VsCode
#
# This script is generated via the command:
# code --list-extensions | xargs -L 1 echo code --install-extension
# Reference: https://stackoverflow.com/questions/35773299/how-can-you-export-vs-code-extension-list
#
# To install:
# ./install-code-exts.sh
code --install-extension aaron-bond.better-comments
code --install-extension aaronthomas.vscode-snazzy-operator
code --install-extension AdamCaviness.theme-monokai-dark-soda
code --install-extension akamud.vscode-theme-onedark
code --install-extension akamud.vscode-theme-onelight
code --install-extension alefragnani.Bookmarks
code --install-extension alefragnani.project-manager
code --install-extension alexdima.copy-relative-path
code --install-extension aliariff.auto-add-brackets
code --install-extension arcticicestudio.nord-visual-studio-code
code --install-extension austin.code-gnu-global
code --install-extension azemoh.one-monokai
code --install-extension benvp.vscode-hex-pm-intellisense
code --install-extension brittanychiang.halcyon-vscode
code --install-extension bungcip.better-toml
code --install-extension christian-kohler.npm-intellisense
code --install-extension christian-kohler.path-intellisense
code --install-extension chun.vscode-translate
code --install-extension codezombiech.gitignore
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension cometeer.spacemacs
code --install-extension Connorcpu.vsc-rustfmt
code --install-extension daltonjorge.scala
code --install-extension Dart-Code.dart-code
code --install-extension Dart-Code.flutter
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension davidbroetje.algorithm-mnemonics-vscode
code --install-extension dbaeumer.jshint
code --install-extension dbaeumer.vscode-eslint
code --install-extension dcasella.monokai-plusplus
code --install-extension DevonDCarew.bazel-code
code --install-extension donjayamanne.githistory
code --install-extension doublefint.pgsql
code --install-extension dracula-theme.theme-dracula
code --install-extension dunstontc.dark-plus-syntax
code --install-extension eamodio.gitlens
code --install-extension eg2.tslint
code --install-extension eg2.vscode-npm-script
code --install-extension emilast.LogFileHighlighter
code --install-extension emmanuelbeziat.vscode-great-icons
code --install-extension Equinusocio.vsc-material-theme
code --install-extension ericadamski.carbon-now-sh
code --install-extension esbenp.prettier-vscode
code --install-extension evilz.vscode-reveal
code --install-extension fab1o.dark-plus-with-italics
code --install-extension fabiospampinato.vscode-install-vsix
code --install-extension fatihacet.gitlab-workflow
code --install-extension fcrespo82.markdown-table-formatter
code --install-extension felipe-mendes.slack-theme
code --install-extension felipecaputo.git-project-manager
code --install-extension file-icons.file-icons
code --install-extension formulahendry.auto-close-tag
code --install-extension formulahendry.code-runner
code --install-extension fwcd.kotlin
code --install-extension fwcd.kotlindebug
code --install-extension GrapeCity.gc-excelviewer
code --install-extension Gruntfuggly.todo-tree
code --install-extension heptio.jsonnet
code --install-extension HookyQR.beautify
code --install-extension humao.rest-client
code --install-extension igochkov.vscode-ebnf
code --install-extension ionutvmi.path-autocomplete
code --install-extension ipedrazas.kubernetes-snippets
code --install-extension ivomachado.configure-c-compiling
code --install-extension JakeBecker.elixir-ls
code --install-extension jakeboone02.cypher-query-language
code --install-extension jbenden.c-cpp-flylint
code --install-extension jebbs.plantuml
code --install-extension joaompinto.asciidoctor-vscode
code --install-extension joaompinto.vscode-graphviz
code --install-extension jolaleye.horizon-theme-vscode
code --install-extension JPTarquino.postgresql
code --install-extension junv.recent-files
code --install-extension karyfoundation.theme-karyfoundation-themes
code --install-extension kenhowardpdx.vscode-gist
code --install-extension keyring.Lua
code --install-extension KnisterPeter.vscode-github
code --install-extension kumar-harsh.graphql-for-vscode
code --install-extension kvnxush.one-dark-operator-theme
code --install-extension lextudio.restructuredtext
code --install-extension lkytal.FlatUI
code --install-extension maddouri.cmake-tools-helper
code --install-extension maelvalais.autoconf
code --install-extension marcochavezf.darcula-operator-mono-vscode
code --install-extension mariorodeghiero.vue-theme
code --install-extension markfknight.monokai-operator-theme
code --install-extension marlon407.code-groovy
code --install-extension mathiasfrohlich.Kotlin
code --install-extension mauve.terraform
code --install-extension mikey.vscode-fileheader
code --install-extension mirkoh.cpp-symbols
code --install-extension mitaki28.vscode-clang
code --install-extension mjmcloug.vscode-elixir
code --install-extension momoto.binary-viewer
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-mssql.mssql
code --install-extension ms-python.python
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.Go
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension mushan.vscode-open-iterm2
code --install-extension naco-siren.gradle-language
code --install-extension panicbit.cargo
code --install-extension patrys.vscode-code-outline
code --install-extension peterj.proto
code --install-extension PeterJausovec.vscode-docker
code --install-extension piotrpalarz.vscode-gitignore-generator
code --install-extension PKief.material-icon-theme
code --install-extension pnp.polacode
code --install-extension quicktype.quicktype
code --install-extension redhat.java
code --install-extension redhat.vscode-yaml
code --install-extension remimarsal.prettier-now
code --install-extension RolandGreim.sharecode
code --install-extension rprouse.theme-obsidian
code --install-extension rubbersheep.gi
code --install-extension rust-lang.rust
code --install-extension serayuzgur.crates
code --install-extension shaharkazaz.git-merger
code --install-extension Shan.code-settings-sync
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension shuworks.vscode-table-formatter
code --install-extension SolarLiner.linux-themes
code --install-extension streetsidesoftware.avro
code --install-extension sveggiani.vscode-field-lights
code --install-extension teabyii.ayu
code --install-extension techer.open-in-browser
code --install-extension technosophos.vscode-helm
code --install-extension thenikso.github-plus-theme
code --install-extension thomaspink.theme-github
code --install-extension tomoki1207.pdf
code --install-extension trinm1709.dracula-theme-from-intellij
code --install-extension trixnz.go-to-method
code --install-extension twxs.cmake
code --install-extension vangware.dark-plus-material
code --install-extension vector-of-bool.cmake-tools
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vncz.vscode-apielements
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-maven
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vscodevim.vim
code --install-extension waderyan.gitblame
code --install-extension wayou.vscode-todo-highlight
code --install-extension webdokkeren.joinlines
code --install-extension webfreak.debug
code --install-extension whizkydee.material-palenight-theme
code --install-extension wholroyd.HCL
code --install-extension wlhe.c-cpp-snippets
code --install-extension xaver.clang-format
code --install-extension yzane.markdown-pdf
code --install-extension yzhang.markdown-all-in-one
code --install-extension zhuangtongfa.Material-theme
code --install-extension zxh404.vscode-proto3
